"use client";

import { memo, useMemo } from "react";
import ReactMarkdown from "react-markdown";
import { Cpu } from "lucide-react";
import type { ReportType } from "@/lib/types";
import { getModelMeta } from "@/lib/models";

interface TlpStyle {
  bg: string;
  border: string;
  text: string;
  label: string;
  statement: string;
}

const TLP_STYLES: Record<ReportType, TlpStyle> = {
  operational: {
    bg: "bg-accent-red",
    border: "border-accent-red/60",
    text: "text-white",
    label: "TLP:RED",
    statement:
      "FOR NAMED RECIPIENTS ONLY. Not for disclosure outside of designated recipients. Sources may specify intended recipients.",
  },
  strategic: {
    bg: "bg-accent-amber",
    border: "border-accent-amber/60",
    text: "text-bg",
    label: "TLP:AMBER+STRICT",
    statement:
      "RESTRICTED TO THE ORGANIZATION ONLY. Recipients may not share outside their organization.",
  },
  external: {
    bg: "bg-accent-green",
    border: "border-accent-green/60",
    text: "text-bg",
    label: "TLP:GREEN",
    statement:
      "COMMUNITY WIDE. Recipients may share within their community or sector, but not via publicly accessible channels.",
  },
};

const REPORT_TITLES: Record<ReportType, string> = {
  operational: "OPERATIONAL / TACTICAL REPORT",
  strategic: "STRATEGIC INTELLIGENCE BRIEF",
  external: "EXTERNAL SHARING PRODUCT",
};

export function TlpBanner({ type }: { type: ReportType }) {
  const s = TLP_STYLES[type];
  return (
    <div className={`flex items-start gap-4 border-y ${s.border} ${s.bg} px-5 py-2.5`}>
      <span className={`text-[12px] font-black tracking-[0.25em] uppercase ${s.text} shrink-0`}>{s.label}</span>
      <span className={`text-[11px] font-medium uppercase tracking-wider ${s.text} opacity-90`}>
        {s.statement}
      </span>
    </div>
  );
}

interface Props {
  content: string;
  type: ReportType;
  modelId?: string;
  modelLabel?: string;
  timestamp?: string;
}

function stripDuplicateTlpHeader(content: string, label: string): string {
  // The model often prepends a TLP line — strip it because the banner already shows it.
  const trimmed = content.trimStart();
  const firstLine = trimmed.split(/\r?\n/)[0] ?? "";
  if (firstLine.toUpperCase().includes(label)) {
    return trimmed.replace(firstLine, "").replace(/^\s*#+\s*\n?/, "").trimStart();
  }
  return content;
}

export const ReportRenderer = memo(function ReportRenderer({ content, type, modelId, modelLabel, timestamp }: Props) {
  const s = TLP_STYLES[type];
  const label = modelLabel || (modelId ? getModelMeta(modelId).label : null);
  const provider = modelId ? getModelMeta(modelId).provider : null;
  const dot = modelId ? getModelMeta(modelId).dot : null;
  const cleaned = useMemo(() => stripDuplicateTlpHeader(content, s.label), [content, s.label]);
  const markdown = useMemo(() => <ReactMarkdown>{cleaned}</ReactMarkdown>, [cleaned]);

  return (
    <div>
      <TlpBanner type={type} />

      <div className="px-6 pt-6">
        <div className="text-[10px] font-mono tracking-[0.3em] uppercase text-text-muted">
          ARGUS Intelligence Product
        </div>
        <h1 className="mt-1 text-3xl font-black tracking-tight text-text-primary">
          {REPORT_TITLES[type]}
        </h1>
      </div>

      <div className="markdown px-6 pt-2 pb-6">
        {markdown}
        {label && (
          <div className="mt-8 pt-4 border-t border-dashed border-border flex items-center gap-2 text-[11px] text-text-muted">
            <Cpu className="size-3" />
            {dot && <span className={`size-1.5 rounded-full ${dot}`} />}
            <span>
              Generated by <span className="text-text-secondary font-medium">{label}</span>
              {provider && <span className="text-text-muted"> · {provider}</span>}
            </span>
            {timestamp && (
              <span className="ml-auto font-mono">
                {new Date(timestamp).toLocaleString()}
              </span>
            )}
          </div>
        )}
      </div>
      <TlpBanner type={type} />
    </div>
  );
});
